name: Build Android

on:
  workflow_dispatch

jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Config Gradle
        run: |
          sed -i '/signingConfigs {/,/^    }/d' android/app/build.gradle.kts
          sed -i '/buildTypes {/,/^    }/d' android/app/build.gradle.kts
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Setup Flutter
        uses: bancolombia/flutter-setup-action@main
        with:
          channel: 'stable'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build boilerplate code
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Try to change compileSdkVersion for rhttp
        run: sed -i 's/\(compileSdkVersion\) 33/\1 34/' /home/runner/.pub-cache/hosted/pub.dev/rhttp-0.15.0/android/build.gradle
        continue-on-error: true
      - name: Build apk
        run: flutter build apk --split-per-abi --dart-define=IS_GOOGLEPLAY=false
      - name: Sign APK
        uses: NoCrypt/sign-android@main
        with:
          releaseDir: build/app/outputs/flutter-apk
          signingKey: ${{ secrets.KEYSTORE }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Upload arm64 build artifact
        uses: actions/upload-artifact@main
        with:
          name: arm64
          path: build/app/outputs/flutter-apk/*arm64*signed.apk
      - name: Upload armeabi-v7a build artifact
        uses: actions/upload-artifact@main
        with:
          name: armeabi-v7a
          path: build/app/outputs/flutter-apk/*armeabi-v7a*signed.apk
      - name: Upload x86_64 build artifact
        uses: actions/upload-artifact@main
        with:
          name: x86_64
          path: build/app/outputs/flutter-apk/*x86_64*signed.apk
      - name: List files
        if: always()
        run: tree
